### ISSUE TITLE
Saving to disk as Image

### ISSUE THREAD

**Issue by dbd5** [yzalis/Identicon#12]
Hi,

Is there a method to save the identicon to disk as image once it is created?

Thanks

**Comment by blaugueux** [comment]
Hi @dbd5, there is no method yet to do that. Feel free to open a PR I'll be happy to merge it :)

**Comment by dbd5** [comment]
Ok, thanks

**Comment by mezklador** [comment]
Maybe it's easy to write few lines of code, like this:
```
$img = new \Identicon\Identicon();

ob_start();
    $img->getImage('foo@bar.baz');
    $identicon = ob_get_contents();
ob_end_clean();

$path = '/your/path/to/save/img/';
$filename = 'foo_at_bar_baz';
if (!file_exists($path . $filename)
    file_put_contents($path . $filename, $identicon);
```

Or maybe it could be possible to inject a method (named, for ex.: saveImageToFile($filepath, $filename, $size)) with those lines of code?

**Comment by blaugueux** [comment]
I think it should be interesting to have this feature directly inside the lib.

**Comment by blaugueux** [comment]
@dbd5 Do you plan to submit a PR or should I close your issue?

**Comment by dbd5** [comment]
Hi @blaugueux , will be glad to but a bit tied up for the present.
This is more of a feature request now so I will go ahead and close the issue, we will revisit this again
