### ISSUE TITLE
hellow man i work with laravel and i host in heroku app

### ISSUE THREAD

**Issue by amine8ghandi8amine** [yzalis/Identicon#66]
Whoops, looks like something went wrong.

1/1
Exception in /app/vendor/yzalis/identicon/src/Identicon/Generator/GdGenerator.php line 15:
GD does not appear to be avaliable in your PHP installation. Please try another generator
---------------------------------------
when i search i found that

the line 15 should be like that

        if (!extension_loaded('gd') && !extension_loaded('ext-gd') ) {

----------------

cause herku work with ext-gd can you fi that cause heroku install your repo automatically i cant change it by my one thanx

**Comment by blaugueux** [comment]
Hi @amine8ghandi8amine. Fix has been merged 3440ff5c3d20e7d4982cd8c2c5d2d785bb84a418.
